name: Matrix demo
on: push
jobs:
  build:
    continue-on-error: true 
    strategy:
      matrix:
        #node-version et operating-system sont les axes de la matrice
        # et ne sont pas des noms réservés
        node-version: [12, 18, 20]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          # Add macOS with Node 20
          - node-version: 20
            operating-system: macos-latest
        exclude:
          # Exclude Node 12 on Windows
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
    